# Any time a "version" tag is pushed (via the "Version Bump" workflow)
# We will deploy and publish the Nerdpack to New Relic One
name: New Relic One Publish & Deploy on tag
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    env:
      NR1_PROFILE: nr1-in-docker
      NR1_REGION: us
      NR1_CHANNEL: DEV

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install nr1 CLI
      run: curl -s https://cli.nr-ext.net/installer.sh | bash
    - name: Publish and deploy the Nerdpack
      run: |
        nr1 profiles:add --name "$NR1_PROFILE" --api-key "${{secrets.NR1_API_KEY}}" --region "$NR1_REGION" &&
        nr1 nerdpack:publish --profile="$NR1_PROFILE" &&
        nr1 nerdpack:deploy --channel="$NR1_CHANNEL"
