# Any time a "version" tag is pushed (via the "Version Bump" workflow)
# We will deploy and publish the Nerdpack to New Relic One

name: New Relic One Publish & Deploy on tag
on:
  push:
    tags:
      - 'v*'
jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: metavida/nr1-publish-and-deploy@2ebe0227
      with:
        api-key: ${{ secrets.NR_PERSONAL_API_KEY }}
        region: us
