# Any time a commit lands on master:
# * increment the version number
# * add a version tag
# * and push the new commit & tag to GitHub.

name: Version Bump
on:
  push:
    branches:
      - 'master'
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup git user
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@example.com"
    - name: Bump the Nerdpack version
      run: npm version patch
    - name: Push changes
      run: git push --tags master origin/master
